### ISSUE TITLE
[Bug]: Excavator action fails due to permisisons

### ISSUE THREAD

**Issue by jhotmann** [ScoopInstaller/BucketTemplate#8]
### Prerequisites

- [X] I have written a descriptive issue title.
- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.
- [X] I have verified that I am using the latest version of Scoop and corresponding bucket.

### Package Name

N/A

### Expected/Current Behaviour

The Excavator job should complete without failure.

### Steps to Reproduce

I create a new bucket repository from this template. The Excavator job has always failed with this message:

```
$ git push origin master
remote: Permission to my/bucket.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/my/bucket.git/': The requested URL returned error: 403
```

### Possible Solution

Excavator workflow should state needed permissions

```
on:
  workflow_dispatch:
  schedule:
    # run every 4 hours
    - cron: '20 */4 * * *'
permissions:
  contents: write
name: Excavator
jobs:
  excavate:
    name: Excavate
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@main
      - name: Excavate
        uses: ScoopInstaller/GithubActions@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SKIP_UPDATED: 1
```

### Scoop and Buckets Version

```console
N/A - GitHub Actions issue
```

### Scoop Config

```console
N/A - GitHub Actions issue
```

### PowerShell Version

```console
N/A - GitHub Actions issue
```
